### ISSUE TITLE
order matters

### ISSUE THREAD

**Issue by zerwes** [Rosa-Luxemburgstiftung-Berlin/ansible-role-haproxy#11]
for example, in a frontend definition
```
acl tls req.ssl_hello_type 1
tcp-request content accept if tls
```
works, but with inverse order it will cause a error
`'tcp-request content accept' : error detected in frontend '...' while parsing 'if' condition : no such ACL : 'tls'`

**Comment by zerwes** [comment]
use
```yaml
haproxy_frontends:
  - name: ...
    acl:
      - tls req.ssl_hello_type 1
    tcp-request:
      - content accept if tls
```
this will put the cfg values in the right order
